# `ParseMachine` subclasses `StateMachine` from invoke's vendored `fluidity` upstream. That base is
# deliberately dropped rather than stubbed: vendoring a stub for a vendored library doubles the
# surface this distribution has to track, and `ParseMachine` is internal machinery no consumer
# constructs or subclasses — `Parser` and `ParseResult` are the names `invoke/__init__.py` exports.

from collections.abc import Iterable
from typing import Any

from invoke.util import Lexicon

from .context import ParserContext

def is_flag(value: str) -> bool: ...
def is_long_flag(value: str) -> bool: ...

class ParseResult(list[ParserContext]):
    unparsed: list[str]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Parser:
    def __init__(
        self,
        contexts: Iterable[ParserContext] = ...,
        initial: ParserContext | None = ...,
        ignore_unknown: bool = ...,
    ) -> None: ...
    def parse_argv(self, argv: list[str]) -> ParseResult: ...

class ParseMachine:
    initial_state: str
    result: ParseResult
    def __init__(self, initial: ParserContext, contexts: Lexicon, ignore_unknown: bool) -> None: ...
    def changing_state(self, from_: str, to: str) -> None: ...
    @property
    def waiting_for_flag_value(self) -> bool: ...
    def handle(self, token: str) -> None: ...
    def store_only(self, token: str) -> None: ...
    def complete_context(self) -> None: ...
    def switch_to_context(self, name: str) -> None: ...
    def complete_flag(self) -> None: ...
    def check_ambiguity(self, value: Any) -> bool: ...
    def switch_to_flag(self, flag: str, inverse: bool = ...) -> None: ...
    def see_value(self, value: Any) -> None: ...
    def see_positional_arg(self, value: Any) -> None: ...
    def error(self, msg: str) -> None: ...
