from types import ModuleType
from typing import Any

from .parser import ParserContext
from .tasks import Task
from .util import Lexicon

class Collection:
    auto_dash_names: bool
    collections: Lexicon[Collection]
    default: str | None
    loaded_from: str | None
    name: str | None
    tasks: Lexicon[Task[Any]]
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __bool__(self) -> bool: ...
    @classmethod
    def from_module(
        cls,
        module: ModuleType,
        name: str | None = ...,
        config: dict[str, Any] | None = ...,
        loaded_from: str | None = ...,
        auto_dash_names: bool | None = ...,
    ) -> Collection: ...
    def add_task(
        self, task: Task[Any], name: str | None = ..., aliases: tuple[str, ...] | None = ..., default: bool | None = ...
    ) -> None: ...
    def add_collection(self, coll: Collection, name: str | None = ..., default: bool | None = ...) -> None: ...
    def subcollection_from_path(self, path: str) -> Collection: ...
    def __getitem__(self, name: str | None = ...) -> Any: ...
    def task_with_config(self, name: str | None) -> tuple[str, dict[str, Any]]: ...
    def __contains__(self, name: str) -> bool: ...
    def to_contexts(self, ignore_unknown_help: bool | None = ...) -> list[ParserContext]: ...
    def subtask_name(self, collection_name: str, task_name: str) -> str: ...
    def transform(self, name: str) -> str: ...
    @property
    def task_names(self) -> dict[str, list[str]]: ...
    def configuration(self, taskpath: str | None = ...) -> dict[str, Any]: ...
    def configure(self, options: dict[str, Any]) -> None: ...
    def serialized(self) -> dict[str, Any]: ...
