from collections.abc import Iterator
from os import PathLike
from typing import Any

def load_source(name: str, path: str) -> dict[str, Any]: ...

class DataProxy:
    @classmethod
    def from_data(
        cls, data: dict[str, Any], root: DataProxy | None = ..., keypath: tuple[str, ...] = ...
    ) -> DataProxy: ...
    def __getattr__(self, key: str) -> Any: ...
    def __setattr__(self, key: str, value: Any) -> None: ...
    def __iter__(self) -> Iterator[dict[str, Any]]: ...
    def __eq__(self, other: object) -> bool: ...
    def __len__(self) -> int: ...
    # Widened from invoke's own `value: str`, which is narrower than the runtime: `_config[key]`
    # takes anything, and config values are routinely ints and bools. Mirroring upstream here would
    # reject `config["timeout"] = 30`. One of the few places these stubs deliberately disagree with
    # invoke's annotation rather than transcribe it, so a regeneration must not quietly revert it.
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def __delitem__(self, key: str) -> None: ...
    def __delattr__(self, name: str) -> None: ...
    def clear(self) -> None: ...
    def pop(self, *args: Any) -> Any: ...
    def popitem(self) -> Any: ...
    def setdefault(self, *args: Any) -> Any: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...

class Config(DataProxy):
    prefix: str
    file_prefix: str | None
    env_prefix: str | None

    @staticmethod
    def global_defaults() -> dict[str, Any]: ...
    def __init__(
        self,
        overrides: dict[str, Any] | None = ...,
        defaults: dict[str, Any] | None = ...,
        system_prefix: str | None = ...,
        user_prefix: str | None = ...,
        project_location: PathLike[str] | None = ...,
        runtime_path: PathLike[str] | None = ...,
        lazy: bool = ...,
    ) -> None: ...
    def load_base_conf_files(self) -> None: ...
    def load_defaults(self, data: dict[str, Any], merge: bool = ...) -> None: ...
    def load_overrides(self, data: dict[str, Any], merge: bool = ...) -> None: ...
    def load_system(self, merge: bool = ...) -> None: ...
    def load_user(self, merge: bool = ...) -> None: ...
    def load_project(self, merge: bool = ...) -> None: ...
    def set_runtime_path(self, path: PathLike[str] | None) -> None: ...
    def load_runtime(self, merge: bool = ...) -> None: ...
    def load_shell_env(self) -> None: ...
    def load_collection(self, data: dict[str, Any], merge: bool = ...) -> None: ...
    def set_project_location(self, path: PathLike[str] | str | None) -> None: ...
    def merge(self) -> None: ...
    def clone(self, into: type[Config] | None = ...) -> Config: ...

class AmbiguousMergeError(ValueError): ...

def merge_dicts(base: dict[str, Any], updates: dict[str, Any]) -> dict[str, Any]: ...
def copy_dict(source: dict[str, Any]) -> dict[str, Any]: ...
def excise(dict_: dict[str, Any], keypath: tuple[str, ...]) -> None: ...
def obliterate(base: dict[str, Any], deletions: dict[str, Any]) -> None: ...
