from contextlib import contextmanager
from os import PathLike
from typing import Any, Generator

from .config import Config, DataProxy
from .runners import Result

class Context(DataProxy):
    command_prefixes: list[str]
    command_cwds: list[str]
    remainder: str

    def __init__(self, config: Config | None = ..., remainder: str = ...) -> None: ...
    @property
    def config(self) -> Config: ...
    @config.setter
    def config(self, value: Config) -> None: ...
    def run(self, command: str, **kwargs: Any) -> Result: ...
    def sudo(self, command: str, **kwargs: Any) -> Result: ...
    @contextmanager
    def prefix(self, command: str) -> Generator[None, None, None]: ...
    @property
    def cwd(self) -> str: ...
    @contextmanager
    def cd(self, path: PathLike[str] | str) -> Generator[None, None, None]: ...

class MockContext(Context):
    def __init__(self, config: Config | None = ..., **kwargs: Any) -> None: ...
    def run(self, command: str, *args: Any, **kwargs: Any) -> Result: ...
    def sudo(self, command: str, *args: Any, **kwargs: Any) -> Result: ...
    def set_result_for(self, attname: str, command: str, result: Result) -> None: ...
