from .parser import ParserContext
from .runners import Result
from .util import ExceptionWrapper

class CollectionNotFound(Exception):
    name: str
    start: str
    def __init__(self, name: str, start: str) -> None: ...

class Failure(Exception):
    reason: WatcherError | None
    result: Result
    def __init__(self, result: Result, reason: WatcherError | None = ...) -> None: ...
    def streams_for_display(self) -> tuple[str, str]: ...

class UnexpectedExit(Failure): ...

class CommandTimedOut(Failure):
    timeout: int
    def __init__(self, result: Result, timeout: int) -> None: ...

class AuthFailure(Failure):
    prompt: str
    result: Result
    def __init__(self, result: Result, prompt: str) -> None: ...

class ParseError(Exception):
    context: ParserContext | None
    def __init__(self, msg: str, context: ParserContext | None = ...) -> None: ...

class Exit(Exception):
    message: str | None
    def __init__(self, message: str | None = ..., code: int | None = ...) -> None: ...
    @property
    def code(self) -> int: ...

class PlatformError(Exception): ...
class AmbiguousEnvVar(Exception): ...
class UncastableEnvVar(Exception): ...
class UnknownFileType(Exception): ...
class UnpicklableConfigMember(Exception): ...

class ThreadException(Exception):
    exceptions: tuple[ExceptionWrapper, ...] = ...

    def __init__(self, exceptions: list[ExceptionWrapper]) -> None: ...

class WatcherError(Exception): ...
class ResponseNotAccepted(WatcherError): ...
class SubprocessPipeError(Exception): ...
