from importlib.machinery import ModuleSpec
from types import ModuleType
from typing import Any

from . import Config

class Loader:
    config: Config | None
    def __init__(self, config: Config | None = ...) -> None: ...
    def find(self, name: str) -> ModuleSpec | None: ...
    def load(self, name: str | None = ...) -> tuple[ModuleType, str]: ...

class FilesystemLoader(Loader):
    def __init__(self, start: str | None = ..., **kwargs: Any) -> None: ...
    @property
    def start(self) -> str: ...
    def find(self, name: str) -> ModuleSpec | None: ...
