from typing import Sequence

from . import Collection, Config, Executor
from .loader import Loader
from .parser import Argument, Parser, ParserContext, ParseResult
from .util import Lexicon

class Program:
    collection: Collection
    config: Config
    config_class: type[Config] | None
    core_via_tasks: ParserContext
    executor_class: type[Executor] | None
    list_depth: int | None
    list_format: str
    list_root: str | None
    loader_class: type[Loader] | None
    namespace: Collection | None
    parser: Parser
    scoped_collection: Collection
    tasks: ParseResult
    version: str | None
    core: ParseResult

    def core_args(self) -> list[Argument]: ...
    def task_args(self) -> list[Argument]: ...
    argv: list[str]
    leading_indent_width: int
    leading_indent: str
    indent_width: int
    indent: str
    col_padding: int

    def __init__(
        self,
        version: str | None = ...,
        namespace: Collection | None = ...,
        name: str | None = ...,
        binary: str | None = ...,
        loader_class: type[Loader] | None = ...,
        executor_class: type[Executor] | None = ...,
        config_class: type[Config] | None = ...,
        binary_names: list[str] | None = ...,
    ) -> None: ...
    def create_config(self) -> None: ...
    def update_config(self, merge: bool = ...) -> None: ...
    def run(self, argv: list[str] | None = ..., exit: bool = ...) -> None: ...
    def parse_core(self, argv: list[str] | None) -> None: ...
    def parse_collection(self) -> None: ...
    def parse_cleanup(self) -> None: ...
    def no_tasks_given(self) -> None: ...
    def execute(self) -> None: ...
    def normalize_argv(self, argv: list[str] | None) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def called_as(self) -> str: ...
    @property
    def binary(self) -> str: ...
    @property
    def binary_names(self) -> list[str]: ...
    @property
    def args(self) -> Lexicon: ...
    @property
    def initial_context(self) -> ParserContext: ...
    def print_version(self) -> None: ...
    def print_help(self) -> None: ...
    def parse_core_args(self) -> None: ...
    def load_collection(self) -> None: ...
    def parse_tasks(self) -> None: ...
    def print_task_help(self, name: str) -> None: ...
    def list_tasks(self) -> None: ...
    def list_flat(self) -> None: ...
    def list_nested(self) -> None: ...
    def list_json(self) -> None: ...
    def task_list_opener(self, extra: str = ...) -> str: ...
    def display_with_columns(self, pairs: Sequence[tuple[str, str | None]], extra: str = ...) -> None: ...
    def print_columns(self, tuples: Sequence[tuple[str, str | None]]) -> None: ...
