import threading
from contextlib import AbstractContextManager
from subprocess import Popen
from types import TracebackType
from typing import IO, Any, Callable, Generator

from .context import Context

# `Failure` is defined in `.exceptions`, but invoke's own `__init__.py` re-exports it from here
# (`from .runners import Failure, Local, Promise, Result, Runner`), so this module has to carry it
# or that re-export dangles. `as Failure` because a stub's imports are private unless redundantly
# aliased, and the package `__init__.pyi` imports it from this module by name.
from .exceptions import Failure as Failure
from .util import ExceptionHandlingThread
from .watchers import StreamWatcher

class Runner:
    context: Context
    encoding: str
    env: dict[str, Any]
    program_finished: threading.Event
    result_kwargs: dict[str, Any]
    streams: dict[str, IO[Any]]
    warned_about_pty_fallback: bool
    watchers: list[StreamWatcher]
    opts: dict[str, Any]
    using_pty: bool
    read_chunk_size: int
    input_sleep: float

    def __init__(self, context: Context) -> None: ...
    def run(self, command: str, **kwargs: Any) -> Result: ...
    def echo(self, command: str) -> None: ...
    def make_promise(self) -> Promise: ...
    def create_io_threads(self) -> tuple[dict[Callable[..., Any], ExceptionHandlingThread], list[str], list[str]]: ...
    def generate_result(self, **kwargs: Any) -> Result: ...
    def read_proc_output(self, reader: Callable[..., Any]) -> Generator[str, None, None]: ...
    def write_our_output(self, stream: IO[Any], string: str) -> None: ...
    def handle_stdout(self, buffer_: list[str], hide: bool, output: IO[Any]) -> None: ...
    def handle_stderr(self, buffer_: list[str], hide: bool, output: IO[Any]) -> None: ...
    def read_our_stdin(self, input_: IO[Any]) -> str | None: ...
    def handle_stdin(self, input_: IO[Any], output: IO[Any], echo: bool = ...) -> None: ...
    def should_echo_stdin(self, input_: IO[Any], output: IO[Any]) -> bool: ...
    def respond(self, buffer_: list[str]) -> None: ...
    def generate_env(self, env: dict[str, Any], replace_env: bool) -> dict[str, Any]: ...
    def should_use_pty(self, pty: bool, fallback: bool) -> bool: ...
    @property
    def has_dead_threads(self) -> bool: ...
    def wait(self) -> None: ...
    def write_proc_stdin(self, data: str) -> None: ...
    def decode(self, data: bytes) -> str: ...
    @property
    def process_is_finished(self) -> bool: ...
    def start(self, command: str, shell: str, env: dict[str, Any]) -> None: ...
    def start_timer(self, timeout: int) -> None: ...
    def read_proc_stdout(self, num_bytes: int) -> bytes | None: ...
    def read_proc_stderr(self, num_bytes: int) -> bytes | None: ...
    def close_proc_stdin(self) -> None: ...
    def default_encoding(self) -> str: ...
    def send_interrupt(self, interrupt: KeyboardInterrupt) -> None: ...
    def returncode(self) -> int | None: ...
    def stop(self) -> None: ...
    def kill(self) -> None: ...
    @property
    def timed_out(self) -> bool: ...
    def get_pid(self) -> int | None: ...

class Local(Runner):
    process: Popen[Any]
    status: int
    def __init__(self, context: Context) -> None: ...
    def should_use_pty(self, pty: bool = ..., fallback: bool = ...) -> bool: ...
    def read_proc_stdout(self, num_bytes: int) -> bytes | None: ...
    def read_proc_stderr(self, num_bytes: int) -> bytes | None: ...
    def close_proc_stdin(self) -> None: ...
    def start(self, command: str, shell: str, env: dict[str, Any]) -> None: ...
    def get_pid(self) -> int: ...
    def kill(self) -> None: ...
    @property
    def process_is_finished(self) -> bool: ...
    def returncode(self) -> int | None: ...
    def stop(self) -> None: ...

class Result:
    command: str
    disowned: bool
    encoding: str | None
    env: dict[str, Any] | None
    exited: int
    hide: tuple[str, ...]
    pid: int | None
    pty: bool
    shell: str
    stderr: str
    stdout: str
    def __init__(
        self,
        stdout: str = ...,
        stderr: str = ...,
        encoding: str | None = ...,
        command: str = ...,
        shell: str = ...,
        env: dict[str, Any] | None = ...,
        exited: int = ...,
        pty: bool = ...,
        hide: tuple[str, ...] = ...,
        pid: int | None = ...,
        disowned: bool = ...,
    ) -> None: ...
    @property
    def return_code(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    @property
    def ok(self) -> bool: ...
    @property
    def failed(self) -> bool: ...
    def tail(self, stream: str, count: int = ...) -> str: ...

class Promise(Result, AbstractContextManager):
    runner: Runner

    def __init__(self, runner: Runner) -> None: ...
    def join(self) -> Result: ...
    def __enter__(self) -> Promise: ...
    # `exc_value` is widened to include None against invoke's own annotation, which declares a bare
    # `BaseException` and so does not satisfy `AbstractContextManager.__exit__` — a normal, no-error
    # `with` block passes None for all three.
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_tb: TracebackType | None
    ) -> None: ...
    def __repr__(self) -> str: ...

def normalize_hide(val: Any, out_stream: str | None = ..., err_stream: str | None = ...) -> tuple[str, ...]: ...
def default_encoding() -> str: ...
