# invoke's own module branches on `sys.platform` to define these differently for Windows; the
# signatures are identical on both sides of that branch, so the stub declares them once.

from collections.abc import Generator
from contextlib import contextmanager
from typing import IO, Any

WINDOWS: bool

def pty_size() -> tuple[int, int]: ...
def stdin_is_foregrounded_tty(stream: IO[Any]) -> bool: ...
def cbreak_already_set(stream: IO[Any]) -> bool: ...
@contextmanager
def character_buffered(stream: IO[Any]) -> Generator[None]: ...
def ready_for_reading(input_: IO[Any]) -> bool: ...
def bytes_to_read(input_: IO[Any]) -> int: ...
